services:
  sglang-qwen35-4B:
    image: lmsysorg/sglang:latest
    container_name: sglang-qwen35-4B
    gpus: all
    restart: always

    ports:
      - "8000:8000"

    environment:
      - HF_TOKEN=${HF_TOKEN}
      - SGLANG_ENABLE_SPEC_V2=1
      - HF_HUB_ENABLE_HF_TRANSFER=1

    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface

    entrypoint: sglang serve

    command: --model-path Qwen/Qwen3.5-4B
      --reasoning-parser qwen3
      --tool-call-parser qwen3_coder
      --speculative-algorithm EAGLE
      --speculative-num-steps 3
      --speculative-eagle-topk 1
      --speculative-num-draft-tokens 4
      --enable-flashinfer-allreduce-fusion
      --mamba-scheduler-strategy extra_buffer
      --mem-fraction-static 0.9
      --host 0.0.0.0
      --port "8000"

    shm_size: "16gb"

    logging:
      options:
        max-size: "10m"
        max-file: "3"

  gateway:
    build: ./gateway
    container_name: fastapi-gateway
    restart: always

    depends_on:
      - sglang-qwen35-4B

    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - gateway

    logging:
      options:
        max-size: "10m"
        max-file: "3"
