events {}

http {
    
    # Rate limit: 5 req/sec per IP
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;
    
    # Reject malformed header names
    ignore_invalid_headers on;

    # Blocking header smuggling via underscore variants
    underscores_in_headers off;

    map $http_authorization $auth_ok {
        "~^Bearer\s+soyboy$"  1;
        default               0;
    }

    server {
        listen 80;

        # Rate limit at server level, before auth
        limit_req zone=api_limit burst=10 nodelay;
        limit_req_status 429;

        location / {
            # API Key protection
            if ($auth_ok = 0) {
                return 401;
            }
            
            # Block CRLF header injection
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $remote_addr;
            proxy_set_header Authorization     $http_authorization;
            proxy_set_header Content-Type      $content_type;

            # Explicitly nullify anything that should never reach the backend
            proxy_set_header X-Injected        "";
            proxy_set_header X-Injected2       "";
 
            # Striping the original forwarded headers so clients can't spoof them
            proxy_set_header X-Forwarded-Host  "";
            proxy_set_header X-Forwarded-Proto "";

            # Forward to FastAPI gateway
            proxy_pass http://gateway:9000;
            proxy_http_version 1.1;

            # REQUIRED FOR STREAMING
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_cache off;
            proxy_request_buffering off;
            chunked_transfer_encoding on;

            #LLM timeout
            proxy_read_timeout 300;
        }
    }
}
